/** Canonical in-app routes — always use drawer shell or modals, never legacy (tabs). */
export const routes = {
  today: '/(drawer)/today',
  history: '/(drawer)/history',
  tracking: '/(drawer)/tracking',
  account: '/(drawer)/account',
  streaks: '/(drawer)/streaks',
  wellness: '/(drawer)/wellness',
  wellnessEntry: '/(modals)/wellness-entry',
  wellnessBaseline: '/(modals)/wellness-baseline',
  doctorVisits: '/(drawer)/doctor-visits',
  doctorAppointment: '/(modals)/doctor-appointment',
  medicalRecords: '/(drawer)/medical-records',
  interactions: '/(drawer)/interactions',
  help: '/(drawer)/help',
  login: '/',
  medicationNew: '/(modals)/medications/new',
  medicationEdit: (id: string) => `/(modals)/medications/${id}` as const,
  supplementNew: '/(modals)/supplements/new',
  supplementEdit: (id: string) => `/(modals)/supplements/${id}` as const,
  reorder: '/(modals)/reorder',
} as const;
